# Default language to use
defaultLanguage: en-US

# Enabled languages
enabledLanguages:
- en-US
- fk-FK

indexer: elasticsearch
# NOT NEEDED AT THE MOMEMNT
# timezone: "+02:00"

server:
  email: admin@example.com

elasticsearch:
  host: localhost
  port: 9200
  # This limits deep pagination
  maxResultsWindow: 10000

mysql:
  host: localhost
  user: ivis
  password: ivis
  database: ivis
  port: 3306
  charset: utf8mb4
  timezone: local

www:
  # HTTP interface to listen on
  host: 0.0.0.0
  # HTTP(S) port to listen on
  trustedPort: 8443
  trustedPortIsHttps: true
  sandboxPort: 8444
  sandboxPortIsHttps: true
  apiPort: 8445
  apiPortIsHttps: true

  trustedUrlBase: https://localhost:8443
  sandboxUrlBase: https://localhost:8444

  # Secret for signing the session ID cookie
  secret: jd8j3hf785hng783k

  # Session length in seconds when "remember me" is checked
  remember: 2592000 # 30 days

  # Is the server behind a proxy? true/false
  # Set this to true if you are serving IVIS as a virtual domain through Nginx or Apache
  proxy: false

  # maximum POST body size
  postsize: 128MB

  # logger interface for expressjs morgan
  log: dev

# Enable to use Redis session cache or disable if Redis is not installed
redis:
  enabled: false
  host: localhost
  port: 6379
  db: 5
  # Uncomment if your Redis installation requires a password
  # password=""

certs:
  www:
    serverCert: certs/server-crt.pem
    serverKey: certs/server-key.pem

  api:
    caCert: certs/ca-crt.pem
    crl: certs/ca-crl.pem
    serverCert: certs/server-crt.pem
    serverKey: certs/server-key.pem


log:
  # silly|verbose|info|http|warn|error|silent
  level: verbose

tasks:
  # time between all job's time triggers check in seconds
  checkInterval: 10
  runLogRetentionTime: 1
  # upper limit for run's output
  maxRunOutputBytes: 1000000
  # print info message about reaching output limit to the output
  printLimitReachedMessage: true
  python:
    # On Centos7 with SCL use: scl enable rh-python36 -- python3 -m venv
    # [Ubuntu 18.04] If there is error message with Unable to symlink '' to '...',
    # specifying full python3 path might fix that
    venvCmd: "/usr/bin/python3 -m venv"
    subtypes:

predictions:
  arima: true
  neural_network: false

roles:
  global:
    master:
      name: "Master"
      admin: true
      description: "All permissions"
      permissions:
      - rebuildPermissions
      - manageSettings
      - allocateSignalSet
      - editTemplatesWithElevatedAccess
      - showAdmin
      - showAdminWorkspaces
      - showAdminTemplates
      - showAdminJobs
      - showAdminTasks
      - viewSystemTasks
      - showAdminSignalSets
      - showAdminUsers
      - showAdminNamespaces
      rootNamespaceRole: master

  namespace:
    master:
      name: "Master"
      description: "All permissions"
      permissions: ["view", "edit", "delete", "share", "createNamespace", "createTemplate", "createJob", "createTask", "createWorkspace", "createPanel", "createSignal", "createSignalSet", "manageUsers"]
      children:
        namespace: ["view", "edit", "delete", "share", "createNamespace", "createTemplate", "createJob", "createTask", "createWorkspace", "createPanel", "createSignal", "createSignalSet", "manageUsers"]
        template: ["view", "edit", "delete", "share", "execute", "viewFiles", "manageFiles"]
        job: ["view", "edit", "delete", "share", "execute", "viewFiles", "manageFiles"]
        task: ["view", "edit", "delete", "share", "execute", "viewFiles", "manageFiles"]
        workspace: ["view", "edit", "delete", "share", "createPanel"]
        panel: ["view", "edit", "delete", "share"]
        signal: ["view", "edit", "delete", "query", "share"]
        signalSet: ["view", "edit", "delete", "insertRecord", "editRecord", "deleteRecord", "query", "share", "reindex", "createSignal", "manageScripts", "createPrediction"]
        prediction: ["view", "edit", "delete", "share"]

  template:
    master:
      name: "Master"
      description: "All permissions"
      permissions: ["view", "edit", "delete", "share", "execute", "viewFiles", "manageFiles"]

  job:
    master:
      name: "Master"
      description: "All permissions"
      permissions: ["view", "edit", "delete", "share", "execute", "viewFiles", "manageFiles"]

  task:
    master:
      name: "Master"
      description: "All permissions"
      permissions: ["view", "edit", "delete", "share", "execute", "viewFiles", "manageFiles"]

  workspace:
    master:
      name: "Master"
      description: "All permissions"
      permissions: ["view", "edit", "delete", "share", "createPanel"]

  panel:
    master:
      name: "Master"
      description: "All permissions"
      permissions: ["view", "edit", "delete", "share"]

  signal:
    master:
      name: "Master"
      description: "All permissions"
      permissions: ["view", "edit", "delete", "query", "share"]

  signalSet:
    master:
      name: "Master"
      description: "All permissions"
      # Note that the ability to "manageScripts" means that one circumvent the "query" permission on a signal because a script has always access to all signals in the signal set.
      permissions: ["view", "edit", "delete", "insertRecord", "editRecord", "deleteRecord", "query", "share", "reindex", "createSignal", "manageScripts", "createPrediction"]

  prediction:
    master:
      name: "Master"
      description: "All permissions"
      permissions: ["view", "edit", "delete", "share"]