name: IVIS-CORE CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install server
      working-directory: ./server
      run: npm ci
    - name: Test server
      working-directory: ./server
      run: npm test
